### ISSUE TITLE
Current source code?

### ISSUE THREAD

**Issue by mattdeav** [CornflakeWoof/Diablo-Style-Loot-for-Elden-Ring#1]
I've looked at the code and would love to contribute here, like adding misc such as separate accessoryGroup values for the talismans. I saw on the thread you've got that planned to fix but I'd love to help out. Are you open to that?

**Comment by CornflakeWoof** [comment]
I'm very happy to hear you'd like to contribute man! I'll be releasing the Beta 0.5 source code once the main mod goes up, but after that I'll be focusing on a full rewrite of DSL in Godot Engine 4 called DSL Remastered, that'll be open source too if you fancy adding to it!
